[package]
name = "cota-registry-aggregator"
version = "0.1.0"
edition = "2018"

[dependencies]
jsonrpc-http-server = "18.0.0"
env_logger = "0.9"
log = "0.4"
hex = "0.4"
failure = "0.1.5"
crc = "2.1.0"
lazy_static = "1.4"
diesel = { version = "1.4.8", features = ["mysql", "r2d2", "numeric"] }
dotenv = "0.15.0"
serde = { version = "1.0", features = [ "derive" ] }
openssl = { version = "0.10", features = ["vendored"] }
cota-smt = {package = "cota-smt", git = "https://github.com/nervina-labs/cota-smt", branch = "develop"}