[package]
name = "compact-registry-aggregator"
version = "0.1.0"
edition = "2018"

[dependencies]
jsonrpc-http-server = "18.0.0"
hex = "0.4"
failure = "0.1.8"
nft-smt = {package = "compact-nft-smt", git = "https://github.com/nervina-labs/compact-nft-smt", branch = "master"}